project_id = "spb-t4nu9v7279pycm5l"

[functions.scribe-mobile-upload]
verify_jwt = false

[functions.scribe-ocr]
verify_jwt = false

[functions.scribe-queue]
verify_jwt = false

[functions.scribe-library]
verify_jwt = false

[functions.scribe-study]
verify_jwt = false
